# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcb4f361b83083f398ad3776e08a99332e7ddcf244992eea32b1bfb3112e0aa925bdd4769e3bd8f293fd8d03c048c8e55ab47efd1e9337ebc343a3dc97f5f493

test:
  secret_key_base: 25ef7b308cf30fcff131c6483b6dd2caefb66c98d3131b7a0f27fd6030649f49f5a7a63d8806b93118f9c4f5164b55b15527f21353319c2d0c654c0d3c4e3645

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
